[package]
name = "Baas-frontend"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]

[dependencies]
rocket = { version = "0.5.1", features = ["dawn", "template"] }
serde = { version = "1.0", features = ["derive"] }

